version: "3.8"

services:
  service1:
    build:
      context: ./apps/service1
    volumes:
      - ./apps/service1:/app
    ports:
      - "8081:8080"
    environment:
      - APP_ENV=development
    depends_on:
      - service2

  service2:
    build:
      context: ./apps/service2
    volumes:
      - ./apps/service2:/app
    ports:
      - "8082:8080"
    environment:
      - APP_ENV=development
    depends_on:
      - service1
