version: "3.8"

services:
  service1:
    build:
      context: ./apps/service1
    ports:
      - "8081:8080"
    environment:
      - APP_ENV=production
    networks:
      - app-network

  service2:
    build:
      context: ./apps/service2
    ports:
      - "8082:8080"
    environment:
      - APP_ENV=production
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
