// Code generated by json2go; DO NOT EDIT.
// Source: server_management.json

package dto

type ServerManagement struct {
	Name string `json:"name"`
	Description string `json:"description"`
	PortToBind float64 `json:"port_to_bind"`
	PortProxy float64 `json:"port_proxy"`
	Status bool `json:"status"`
}
